
ballot = /packt/images/icons/system/ballot.png
view = /packt/images/icons/system/view.png
clock = /packt/images/icons/system/clock.png
menu_notifications = /packt/images/icons/system/notification.png
email = /packt/images/icons/system/email.png
in_stock =/packt/images/icons/system/in-stock.png
list = /packt/images/icons/system/list.png
menu = /packt/images/icons/system/menu.png
produt = /packt/images/icons/system/produt.png
report = /packt/images/icons/system/report.png
stock = /packt/images/icons/system/sotock.png
user = /packt/images/icons/system/user.png
user_add = /packt/images/icons/system/user-add.png
add = /packt/images/icons/system/add.png

app_logo =/packt/images/icons/app-logo.jpg
default_user = /packt/images/icons/system/user.png
dashboard =/packt/images/icons/system/dashboard.png
add_item =/packt/images/icons/system/add-item.png