simple_info_alert=/packt/fxmls/alertas/SimpleInfoAlert.fxml
simple_error_alert=/packt/fxmls/alertas/SimpleErrorAlert.fxml
modal_confirmation_alert=/packt/fxmls/alertas/ModalConfirmationAlert.fxml
non_modal_notification_alert=/packt/fxmls/alertas/NonModalNotificationAlert.fxml
