# Configuração do SQLite
database.sqlite.diretorio=./database
database.sqlite.arquivo=inventario.db
database.sqlite.journal.mode=WAL
database.sqlite.synchronous=NORMAL

# Configuração do DatabaseInitializer
database.initializer.schema.path=/db/schema.sql
database.initializer.migrations.path=/db/migrations
database.initializer.auto-create=true
database.initializer.version=1.0.0

# Configuração do ConexaoVerificador
conexao.verificador.timeout.socket=3000
conexao.verificador.timeout.db=5000
conexao.verificador.porta.padrao=3306
conexao.verificador.threads.pool=2