# database.properties - ATUALIZADO
db.host=localhost
db.port=3306
db.name=gestao_dep_it 
db.user=rafael
db.password=@3570_RT.Mysql

# Parâmetros Otimizados para Produção
db.pool.initialSize=5
db.pool.maxTotal=20
db.pool.maxIdle=10
db.pool.minIdle=5